components:
    schemas:
        Account:
            # @review
            description:
                An account represents an external account, for example a
                customer business.
            properties:
                description:
                    type: string
                domains:
                    # @review
                    description:
                        The account's email domains. Users assigned to this
                        account generally will have email addresses under one
                        of these domains.
                    items:
                        type: string
                    type: array
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                parentAccountId:
                    format: int64
                    type: integer
                status:
                    readOnly: true
                    type: integer
            type: object
info:
    description:
        ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Account Rest"
    version: v1.0
openapi: 3.0.1
paths:
    "/accounts/{accountId}":
        get:
            description:
                ""
            operationId: getAccount
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Account"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Account"
                    description:
                        ""
            tags: ["Account"]